#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#server:
#  port: 8761
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#

# the old config
server.port:
  8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost